version: '3.9'

services:
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: 'ticketing'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - ticketing

  redis:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      retries: 3
      timeout: 5s
    networks:
      - ticketing

  api:
    build:
      context: ./
    image: ticketing-api
    container_name: ticketing-api
    restart: always
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4000']
      interval: 30s
      timeout: 10s
      retries: 5
    depends_on:
      - db
      - redis
    ports:
      - 4000:4000
    environment:
      SECRET_KEY: ticketing-secret-key
      GOD_PASSWORD: ticketing-password
      DB_HOST: db
      DB_PORT: 3306
      DB_USERNAME: root
      DB_PASSWORD: password
      DB_NAME: ticketing
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DEFAULT_TTL: 3600
      REDIS_URL: redis://redis:6379
    links:
      - db
      - redis
    networks:
      - ticketing

networks:
  ticketing:

volumes:
  db:
    driver: local
  redis:
    driver: local
